---
- name: Read passenger_root from system config
  shell: /usr/bin/passenger-config --root
  register: passenger_root
  changed_when: false

- name: Remove default site configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: Configure nginx
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx
