---
- name: Bootstrap Dress to Impress workspace
  # We want developers to be able to work in apps/impress.
  # So, we don't control the pull process (update=no).
  local_action: git repo=https://github.com/openneo/impress dest=apps/impress update=no
  sudo: false

- name: Bootstrap Dress to Impress ENV variables
  # If you override env.yml, we won't replace it. (force=no)
  local_action: template src={{ role_path }}/defaults/env.yml.example dest={{ role_path }}/defaults/env.yml force=no
  sudo: no

- name: Load Dress to Impress ENV variables
  include_vars: "{{ role_path }}/defaults/env.yml"

- name: Write Dress to Impress ENV variables to .env file
  template: src=dotenv dest={{ app_root }}/.env

- name: Install Dress to Impress gems
  bundler: state=present exclude_groups=production chdir={{ app_root }}

- name: Create Impress database
  mysql_db: name=impress
  register: impress_create_db

- name: Bootstrap Impress database
  shell: bundle exec rake db:schema:load db:seed
  args:
    chdir: "{{ app_root }}"
  when: impress_create_db.changed

- name: Install Redis server
  apt: name=redis-server state=latest

- name: Create Resque service
  template: src=resque.init.d dest=/etc/init.d/impress-resque mode="u=rwx,go=rx"
  notify: restart impress-resque

- name: Configure Impress nginx site
  template: src=impress.conf dest=/etc/nginx/sites-enabled/
  notify: reload nginx
