---
- name: Bootstrap Dress to Impress ENV variables
  # If you override env.yml, we won't replace it. (force=no)
  local_action: template src={{ role_path }}/defaults/env.yml.example dest={{ role_path }}/defaults/env.yml force=no
  sudo: no

- name: Load Dress to Impress ENV variables
  include_vars: "{{ role_path }}/defaults/env.yml"

- name: Write Dress to Impress ENV variables to .env file
  template: src=dotenv dest={{ app_root }}/.env

- name: Install Dress to Impress gems
  bundler: state=present exclude_groups=production chdir={{ app_root }}

- name: Create Impress database
  mysql_db: name=impress
  register: impress_create_db

- name: Create database.yml
  copy: src=database.yml dest={{ app_root }}/config/

- name: Bootstrap Impress database
  shell: bundle exec rake db:schema:load db:seed
  args:
    chdir: "{{ app_root }}"
  when: impress_create_db.changed

- name: Bootstrap Impress Elasticsearch index
  # This one's kinda cheating.
  # We assume that the db and ES index are being created at the same time.
  # It's a decent assumption, but it'd be better to check the ES index instead.
  shell: bundle exec rake flex:create_indices
  args:
    chdir: "{{ app_root }}"
  when: impress_create_db.changed

- name: Install Redis server
  apt: name=redis-server state=latest

- name: Create Resque service
  template: src=resque.init.d dest=/etc/init.d/impress-resque mode="u=rwx,go=rx"
  notify: restart impress-resque

- name: Configure Impress nginx site
  template: src=impress.conf dest=/etc/nginx/sites-enabled/
  notify: reload nginx
