---
- name: Bootstrap Dress to Impress workspace
  # We want developers to be able to work in apps/impress.
  # So, we don't control the pull process (update=no).
  local_action: git repo=https://github.com/openneo/impress dest=apps/impress update=no
  sudo: false

- name: Install Dress to Impress gems
  bundler: state=present exclude_groups=production chdir=/vagrant/apps/impress

- name: Bootstrap Dress to Impress ENV variables
  # If you override env.yml, we won't replace it. (force=no)
  local_action: template src={{ role_path }}/defaults/env.yml.example dest={{ role_path }}/defaults/env.yml force=no
  sudo: no

- name: Load Dress to Impress ENV variables
  include_vars: "{{ role_path }}/defaults/env.yml"

- name: Configure Impress nginx site
  template: src=impress.conf dest=/etc/nginx/sites-enabled/impress.conf
  notify: reload nginx
