# Realistically, we should probably move our direct S3 calls to something like CarrierWave,
# which adds an extra abstraction layer so that we can store to filesystem in dev or whatever.
# But, if we can stub this out instead of tearing out our legacy code, I vote that for now xD

---
- name: Create FakeS3 source directory
  file: path={{ fakes3_source_path }} state=directory

- name: Create FakeS3 Gemfile
  # This fork of the gem will respond to TERM signals, so we can stop it as a service.
  # But we gotta jump through more hoops to use it.
  copy: src=Gemfile dest={{ fakes3_source_path }}

- name: Install FakeS3 gem
  bundler: state=present chdir={{ fakes3_source_path }} user_install=no binstub_directory=bin
  notify: restart fakes3

- name: Create FakeS3 data directory
  file: path={{ fakes3_data_path }} state=directory

- name: Install FakeS3 daemon
  template: src=init.d dest=/etc/init.d/fakes3 mode="u=rwx,go=rx"
  notify: restart fakes3
